version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./site:/usr/share/nginx/html
    - ./nginx/localhost.crt:/etc/nginx/localhost.crt
    - ./nginx/localhost.key:/etc/nginx/localhost.key
    ports:
    - "80:80"
    - "443:443"