version: '3.7'
container_name: my-site
services:
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./site:/usr/share/nginx/html
    - ./nginx/my-site.com.crt:/etc/nginx/my-site.com.crt
    - ./nginx/my-site.com.key:/etc/nginx/my-site.com.key
    ports:
    - "80:80"
    - "443:443"